version: "3"
services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    container_name: api
    ports:
      - "80:8080"
    restart: always
    depends_on:
      - db
      - cache
  
  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data/:/docker-entrypoint-initdb.d/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      TZ: "Asia/Tokyo"
  
  cache:
    image: redis:5.0.3-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always